CREATE OR REPLACE PACKAGE "HZ_IMP_PARTIES_T_VAL_PKG" AS
  --+===============================================================+
  --| Module/Object Name: HZ_IMP_PARTIES_T_VAL_PKG.pks                          |
  --|                                                               |
  --| Description: Validation package for HZ_IMP_PARTIES_T            |
  --|              Generated by Conversion Agent Step 3             |
  --|                                                               |
  --| Creation Date: 16-FEB-2026                                       |
  --|                                                               |
  --| Author      : Conversion Agent (Auto-generated)              |
  --+===============================================================+

    /*
    * Procedure to validate and transform batch records
    * Parameters:
    *   p_batch_id - The batch identifier to process
    */
    PROCEDURE validate_batch(p_batch_id IN VARCHAR2);

END HZ_IMP_PARTIES_T_VAL_PKG;
/
