CREATE OR REPLACE PACKAGE BODY "HZ_IMP_PARTIES_T_VAL_PKG" IS
  --+===============================================================+
  --| Module/Object Name: HZ_IMP_PARTIES_T_VAL_PKG.pkb                          |
  --|                                                               |
  --| Description: Validation package body for HZ_IMP_PARTIES_T       |
  --|              Generated by Conversion Agent Step 3             |
  --|                                                               |
  --| Creation Date: 16-FEB-2026                                       |
  --|                                                               |
  --| Author      : Conversion Agent (Auto-generated)              |
  --+===============================================================+

    PROCEDURE validate_batch(p_batch_id IN VARCHAR2) IS
        v_error_count NUMBER := 0;
        v_valid_count NUMBER := 0;
    BEGIN

        /*========== Phase 0: Reset status for batch ==========*/

        UPDATE HZ_IMP_PARTIES_T t
        SET t.status = 'N',
            t.error_message = NULL
        WHERE t.BATCH_ID = p_batch_id;

        COMMIT;

        /*========== Phase 1: Mandatory field checks ==========*/

        -- 1. Mandatory: PARTY_ORIG_SYSTEM
        UPDATE HZ_IMP_PARTIES_T t
        SET t.status = 'E',
            t.error_message = NVL(t.error_message, '') || 'PARTY_ORIG_SYSTEM is mandatory and cannot be NULL; '
        WHERE t.BATCH_ID = p_batch_id
        AND t.PARTY_ORIG_SYSTEM IS NULL;

        -- 2. Mandatory: PARTY_ORIG_SYSTEM_REFERENCE
        UPDATE HZ_IMP_PARTIES_T t
        SET t.status = 'E',
            t.error_message = NVL(t.error_message, '') || 'PARTY_ORIG_SYSTEM_REFERENCE is mandatory and cannot be NULL; '
        WHERE t.BATCH_ID = p_batch_id
        AND t.PARTY_ORIG_SYSTEM_REFERENCE IS NULL;

        -- 3. Mandatory: PARTY_TYPE
        UPDATE HZ_IMP_PARTIES_T t
        SET t.status = 'E',
            t.error_message = NVL(t.error_message, '') || 'PARTY_TYPE is mandatory and cannot be NULL; '
        WHERE t.BATCH_ID = p_batch_id
        AND t.PARTY_TYPE IS NULL;

        -- 4. Mandatory: PARTY_USAGE_CODE
        UPDATE HZ_IMP_PARTIES_T t
        SET t.status = 'E',
            t.error_message = NVL(t.error_message, '') || 'PARTY_USAGE_CODE is mandatory and cannot be NULL; '
        WHERE t.BATCH_ID = p_batch_id
        AND t.PARTY_USAGE_CODE IS NULL;

        -- 5. Mandatory: ORGANIZATION_NAME
        UPDATE HZ_IMP_PARTIES_T t
        SET t.status = 'E',
            t.error_message = NVL(t.error_message, '') || 'ORGANIZATION_NAME is mandatory and cannot be NULL; '
        WHERE t.BATCH_ID = p_batch_id
        AND t.ORGANIZATION_NAME IS NULL;


        COMMIT;

        /*========== Phase 2: Validation checks ==========*/

        -- Validation: INSERT_UPDATE_FLAG - If the column value is NOT NULL, then it should only be 'I' or 'U'
        UPDATE HZ_IMP_PARTIES_T t
        SET t.status = 'E',
            t.error_message = NVL(t.error_message, '') || 'INSERT_UPDATE_FLAG must be one of (''I'', ''U''); '
        WHERE t.BATCH_ID = p_batch_id
        AND t.INSERT_UPDATE_FLAG IS NOT NULL
        AND t.INSERT_UPDATE_FLAG NOT IN ('I', 'U');


        COMMIT;

        /*========== Phase 3: Transformation logic ==========*/

        -- No transformation rules defined.


        COMMIT;

        /*========== Phase 4: Mark valid records ==========*/

        UPDATE HZ_IMP_PARTIES_T t
        SET t.status = 'V'
        WHERE t.BATCH_ID = p_batch_id
        AND t.status = 'N';

        COMMIT;

        /*========== Phase 5: Summary logging ==========*/

        SELECT COUNT(*) INTO v_error_count
        FROM HZ_IMP_PARTIES_T
        WHERE BATCH_ID = p_batch_id AND status = 'E';

        SELECT COUNT(*) INTO v_valid_count
        FROM HZ_IMP_PARTIES_T
        WHERE BATCH_ID = p_batch_id AND status = 'V';

        DBMS_OUTPUT.PUT_LINE('Validation completed for batch: ' || p_batch_id);
        DBMS_OUTPUT.PUT_LINE('Valid records: ' || v_valid_count);
        DBMS_OUTPUT.PUT_LINE('Error records: ' || v_error_count);

        COMMIT;

    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error in validate_batch: ' || SUBSTR(SQLERRM, 1, 2000));
            ROLLBACK;
            RAISE;
    END validate_batch;

END HZ_IMP_PARTIES_T_VAL_PKG;
/
