CREATE OR REPLACE PACKAGE BODY "{{PKG_NAME}}" IS
  --+===============================================================+
  --| Module/Object Name: {{PKG_NAME}}.pkb                          |
  --|                                                               |
  --| Description: Validation package body for {{TABLE_NAME}}       |
  --|              Generated by Conversion Agent Step 3             |
  --|                                                               |
  --| Creation Date: {{DATE}}                                       |
  --|                                                               |
  --| Author      : Conversion Agent (Auto-generated)              |
  --+===============================================================+

    PROCEDURE validate_batch(p_batch_id IN VARCHAR2) IS
        v_error_count NUMBER := 0;
        v_valid_count NUMBER := 0;
    BEGIN

        /*========== Phase 0: Reset status for batch ==========*/

        UPDATE {{TABLE_NAME}} t
        SET t.status = 'N',
            t.error_message = NULL
        WHERE t.{{BATCH_COLUMN}} = p_batch_id;

        COMMIT;

        /*========== Phase 1: Mandatory field checks ==========*/

{{MANDATORY_CHECKS}}

        COMMIT;

        /*========== Phase 2: Validation checks ==========*/

{{VALIDATION_CHECKS}}

        COMMIT;

        /*========== Phase 3: Transformation logic ==========*/

{{TRANSFORMATION_LOGIC}}

        COMMIT;

        /*========== Phase 4: Mark valid records ==========*/

        UPDATE {{TABLE_NAME}} t
        SET t.status = 'V'
        WHERE t.{{BATCH_COLUMN}} = p_batch_id
        AND t.status = 'N';

        COMMIT;

        /*========== Phase 5: Summary logging ==========*/

        SELECT COUNT(*) INTO v_error_count
        FROM {{TABLE_NAME}}
        WHERE {{BATCH_COLUMN}} = p_batch_id AND status = 'E';

        SELECT COUNT(*) INTO v_valid_count
        FROM {{TABLE_NAME}}
        WHERE {{BATCH_COLUMN}} = p_batch_id AND status = 'V';

        DBMS_OUTPUT.PUT_LINE('Validation completed for batch: ' || p_batch_id);
        DBMS_OUTPUT.PUT_LINE('Valid records: ' || v_valid_count);
        DBMS_OUTPUT.PUT_LINE('Error records: ' || v_error_count);

        COMMIT;

    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error in validate_batch: ' || SUBSTR(SQLERRM, 1, 2000));
            ROLLBACK;
            RAISE;
    END validate_batch;

END {{PKG_NAME}};
/
